spring:
  application:
    name: pizza-fracaroli
  datasource:
    schema: classpath:db/drop_create_schema.sql
    url: jdbc:mysql://localhost:3306/pizza-fracaroli
    testWhileIdle: true
    validationQuery: SELECT 1
    platform: mysql
    initialization-mode: always
    username: root
    password: pizza-fracaroli100*
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        cache:
          use-query-cache: true
          jdbc:
           lob:
             non_contextual_creation: true
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: pizza-fracaroli
    url: ${spring.datasource.url}
    locations: classpath:db/migration,classpath:db/migration-data
    baseline-on-migrate: true
    table: version
    placeholderReplacement: false
    ignore-missing-migrations: true
springdoc:
  api-docs:
    path: /api-docs